#ifndef __CONFIGURATIONS_H
#define __CONFIGURATIONS_H

/* Configurations for the framework */
#define ACTOR_TYPE_COUNT 1
#define LAND_CELL_COUNT 16
#define SQUIRREL_COUNT 40


#define ACTOR_CREATE_TAG 1222
#define LANDCELL_QUERY_TAG 1233
#define LANDCELL_TERMINATE_TAG 1234
#define LANDCELL_ON_HOP_TAG 1235
#define SQUIRREL_PREPROCESS_TAG 1333
#define SQUIRREL_TERMINATE_TAG 1334

#endif